language: minimal

install: true

before_script: pip install --user awscli

script: aws s3 sync . s3://zurich.serverlessdays.io --delete --exclude ".git/*" --exclude .travis.yml --exclude README.md --acl public-read --cache-control max-age=600

after_script: echo Done

notifications:
  email:
    - d.madama@gmail.com
    - stefano.cicatiello@xpeppers.com
